### ISSUE TITLE
Panic when writing nested row from map[string]any

### ISSUE THREAD

**Issue by bench** [parquet-go/parquet-go#304]
**Library version**

```
github.com/parquet-go/parquet-go v0.25.2-0.20250606175114-8a98e7fff8a3
```

**Go environment**

```
GOOS=linux
GOARCH=amd64
GOVERSION=go1.24.0
What did you do?
```
I tried to read a row from a Parquet file containing nested columns, then write it back using the generic map[string]any structure:

```go
row := map[string]any{
    "name":    "John Doe",
    "age":     30,
    "address": map[string]any{"city": "Paris", "country": "France"},
}
err := writer.Write(row)
```

Since the input schema is dynamic and unknown ahead of time, I cannot use predefined Go structs with tags.

**What did you expect to happen?**

I expected the row to be written successfully, with nested fields handled appropriately.

**What actually happened?**

The writer panics at runtime with the following error:
```
panic: reflect: call of reflect.Value.MapIndex on interface Value
```

**Stack trace**
```
panic: reflect: call of reflect.Value.MapIndex on interface Value

goroutine 1 [running]:
reflect.flag.mustBe(...)
    /go/src/reflect/value.go:218
reflect.Value.MapIndex({0x763800?, 0xc00002ea90?, 0x697317?}, {0x755500, 0xc0000f2180, 0x198})
    /go/src/reflect/map_swiss.go:147 +0x21f
github.com/parquet-go/parquet-go.(*Column).Value(...)
    /parquet-go/column.go:189
github.com/parquet-go/parquet-go.deconstructFuncOfGroup.func1(...)
    /parquet-go/row.go:532
github.com/parquet-go/parquet-go.(*Schema).Deconstruct(...)
    /parquet-go/schema.go:285
github.com/parquet-go/parquet-go.(*Writer).Write(...)
    /parquet-go/writer.go:411
main.main()
    /my-project/main.go:58 +0x4af
exit status 2
Additional context
```

The input row comes from a Parquet file read using the same library.

The Parquet file contains a nested structure.

Since the structure is dynamic, I rely on map[string]any to represent it.

I’ve attached a minimal Parquet file that can be used to reproduce the issue.

**Comment by bench** [comment]
up ⤴️

**Comment by bench** [comment]
it seems I am the only one annoyed with this.

**Comment by achille-roussel** [comment]
Hello @bench, thanks for reporting!

I merged a change that should fix this issue https://github.com/parquet-go/parquet-go/pull/338

Thanks for your patience, let me know if you're still observing the problem on the latest version.

**Comment by bench** [comment]
Thx a lot for your job.
will try it very soon.

**Comment by bench** [comment]
hi @achille-roussel !
Just did a test on your branch.
But it seems the problem persists.

An error occurs when deconstructing the row, specifically in the `deconstructFuncOfGroup` function.

In my example I have an input simple file that I need to write in another parquet file.

It that looks like this

```
$ parquet-tools csv testdata/nested.parquet

name,age,address
John Doe,30,"{'city': 'Paris', 'country': 'France'}"
John Doe,31,"{'city': 'Paris', 'country': 'France'}"
John Doe,32,"{'city': 'Paris', 'country': 'France'}"
```

The `deconstructFuncOfGroup` function is called recursively to traverse the tree. 
When it reaches the `address` element (which is itself a tree/map), it calls the `deconstructFunOfLeaf` function (row.go:532), 

```go
f(columns, levels, fields[i].Value(value))
```

but the code to construct the 3rd parameter fails.

Indeed, the function `fields[i].Value(value)` has the effect of calling the function `column.Value()`

```go
func (c *Column) Value(base reflect.Value) reflect.Value {
  return base.MapIndex(reflect.ValueOf(&c.schema.Name).Elem())
}
```

Which results in a call to `base.MapIndex` on a `value` of type Interface and not a map.

The value in question can typically look like that

<img width="523" height="274" alt="Image" src="https://github.com/user-attachments/assets/3530d00c-7a45-4009-b13f-96a2924a8479" />



**Result: the reflect panics package because Kind is not a type map.**

To reproduce the case, it is possible to implement a very simple case


```go
func main() {
  // Open file containing original nested data
  f, _ := os.Open("MY_SIMPLE_FILE_WITH_A_NESTED_COLUMN")
  reader := parquet.NewReader(f)

  // Open a temp file to write into
  writer, err := os.CreateTemp("", "parquet-")
  if err != nil {
    panic(err) 
  }
  defer writer.Close()
  pqWriter := parquet.NewWriter(writer, reader.Schema())
  defer pqWriter.Close()

  // Read one row from original file and write it to new file
  row := make(map[string]any)
  err = reader.Read(&row)
  if err != nil {
    panic(err)
  }

  err = pqWriter.Write(row)
  if err != nil {
    panic(err) 
  }
  pqWriter.Flush()
}

```

**Comment by bench** [comment]
maybe I missed something @achille-roussel ?

**Comment by bench** [comment]
kind reminder ❤️

**Comment by achille-roussel** [comment]
Hello @bench 

I would recommend using `GenericWriter[any]` as demonstrated in https://github.com/parquet-go/parquet-go/pull/389

It's unfortunate that `Writer` has this bug, eventually we'll converge the two types, but for now this is the best workaround I can suggest.

I looked into fixing the root cause of this problem but it turned into a rabbit hole, our time will be better spent leveraging `GenericWriter[T]` I think.
